openapi: 3.0.3

info:
  description: An implementation of Diagnosis Server supporting the Apple/Google Contact Tracing protocol
    hosted on serverless AWS infrastructure. The
  version: 1.0.0
  title: Apple/Google Contact Tracing Diagnosis Server
  license:
    name: MIT License
    url: https://github.com/Co-Epi/data-models/blob/master/LICENSE

paths:
  /diagnosiskeys:
    post:
      summary: Submit a list of diagnosis keys corresponding for the current period.
      description: Submit a list of diagnosis keys corresponding for a given period. The period is set to a time range
        of [today - 14 days, today]. Diagnosis keys are Daily Tracing keys for the current period.
        https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ContactTracing-CryptographySpecification.pdf

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DiagnosisKey'
              minItems: 1
              maxItems: 14
              uniqueItems: true

      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: ${lambda_invoke_arn}
        httpMethod: POST
      responses:
        '200':
          description: Diagnosis Keys uploaded successfully
        '400':
          description: Request Parameter Invalid. Example, diagnosis key is invalid or day number is invalid
        '500':
          description: Internal Server Error


    get:
      summary: Returns a list of diagnosis keys reported during a specified day number and interval number

      parameters:
      - in: query
        name: reportDayNumber
        description: A positive integer corresponding to a specific date when the user reported that they were
          infected to the back-end server. It is calculated as (Number of Seconds since Epoch / 60 * 60 * 24).
          If not provided, current day number is assumed. Note that this is the day when the infection was reported
          and not the day number corresponding to the daily tracing key, i.e. the day when the daily tracing key
          was generated.
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
        example: 18005

      - in: query
        name: intervalNumber
        description: Positive integer that corresponds to a specific fixed time interval since the
          start of the day number calculated as (Number of seconds since start of day number / intervalLength).
          intervalLength is a fixed time interval in seconds, currently set to (60 * 60 * 6) or 6 hours. This length
          may change in future. If not provided, intervalNumber corresponding to the current timestamp is assumed.
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
        example: 4

      - in: query
        name: intervalLength
        description: The interval length in seconds used by the client to calculate intervalNumber. This is just
          required as a sanity check whether the right value was used by the client to calculate the intervalNumber, in
          case the intervalLength changes in future.
          The server will respond with a 401 error code if the interval length does not match the expected length.
        required: false
        schema:
          type: integer
        example: 21600

      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: ${lambda_invoke_arn}
        httpMethod: POST

      responses:
        '200':
          description: List of diagnosis keys reported during the specified reportDayNumber and intervalNumber
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DiagnosisKey'
        '400':
          description: Request Parameter Invalid
        '401':
          description: intervalLengthSeconds is not valid for the specified date
        '500':
          description: Internal Server Error

components:
  schemas:
    DiagnosisKey:
      description: Diagnosis Key is a daily tracing key that is revealed by the client to the server when a user
        wants to report an infection. It consists of the key data and day number. Day number is calculated as
        (Number of Seconds since Epoch) / (60 * 60 * 24)
      type: object
      properties:
        keyData:
          type: string
          description: Base64 encoded key data of diagnosis key
          minLength: 25
          maxLength: 40
        dayNumber:
          type: integer
          format: int64
          description: A unique unsigned integer corresponding to a specific date, calculated as
            (Number of Seconds since Epoch) / (60 * 60 * 24)
          minimum: 0
      example:
        keyData: "NGk1dTZoZDsnbHBbXXA5MAo="
        dayNumber: 18371
